### ISSUE TITLE
No visualizer, only background (no audio data beeing recieved)

### ISSUE THREAD

**Issue by DrDr22** [elias123tre/lively-audio-visualizer#1]
I downloaded the .zip file and just drag and dropd it in to lively it showd up no issue,but when i set it to background the default image was there but the visualizer circle didin't showd up.I tried playing audio but still nothing.Re instaling lively or the .zip also does nothing.
![kép_2021-05-04_220111](https://user-images.githubusercontent.com/83671645/117062830-3d12c400-ad24-11eb-9e95-58fd2a11e72c.png)

**Comment by eliasfloreteng** [comment]
Many factors could lead to the problem you are describing. Firstly, it would be easier to debug the problem if you included some log files. After enabling the wallpaper in lively, press `WIN+R` then write `%LOCALAPPDATA%\Lively Wallpaper\logs`. Then select all the files and drag them to the textbox when responding to this.

**Comment by DrDr22** [comment]
[20210504_142431.txt](https://github.com/elias123tre/lively-audio-visualizer/files/6425256/20210504_142431.txt)
[20210504_153431.txt](https://github.com/elias123tre/lively-audio-visualizer/files/6425257/20210504_153431.txt)
[20210504_215103.txt](https://github.com/elias123tre/lively-audio-visualizer/files/6425258/20210504_215103.txt)
[20210505_080204.txt](https://github.com/elias123tre/lively-audio-visualizer/files/6425259/20210505_080204.txt)
[20210504_140349.txt](https://github.com/elias123tre/lively-audio-visualizer/files/6425260/20210504_140349.txt)
[20210504_142240.txt](https://github.com/elias123tre/lively-audio-visualizer/files/6425261/20210504_142240.txt)

**Comment by eliasfloreteng** [comment]
The issue seems to be related to the lively browser instance itself and not my wallpaper. It also seems you tried the built in audio visualizer wallpaper and that didn't work either. You could try one solution i found [online](https://help.wallpaperengine.io/en/audio/intermittent.html):
> USB / wireless headsets are prone to sound driver issues. For many devices, changing the audio sample rate in the Windows device settings to 44100 Hz permanently fixes the issue:
> Right-click on the audio icon in the tray area in the lower right corner of Windows, select "Open Sound Settings". Click on "Device Properties" in the "Output" section of the window that opens up. Afterwards, click on "Additional device properties", then navigate to the "Advanced" tab. You can change the sampling rate in the menu shown there. The exact location is different on different versions of Windows. if you cannot find this option, search the web for guides on how to change the sampling rate of sound devices for your version of Windows.
> Set the sampling rate to "24 bit, 44100 Hz"

If that doesn't work I am sorry cause im out of ideas. The audio visualizer feature in lively is still in development and yet [not fully supported](https://github.com/rocksdanister/lively/wiki/Web-Guide-II-:-System-Audio-Data). A good idea might be to open an issue on the lively project on github itself: https://github.com/rocksdanister/lively/issues.

**Comment by DrDr22** [comment]
It worked!
Thank you
